customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('masterpage/',views.masterpage,name='masterpage'),
    path('men/',views.men,name='men'),
    path('women/',views.women,name='women'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('logout/',views.logout,name='logout'),
    path('payment/',views.payment,name='payment'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart,name='cart'),
    path('remove_from_cart/<int:product_id>/',views.remove_from_cart,name='remove_from_cart'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:products_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:products_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('masterpage1/',views.masterpage1,name='masterpage1'),
    path('profile/',views.profile,name='profile')





]

easy_shope/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views 
app_name='seller'
urlpatterns=[
    path('s_index/',views.s_index,name='s_index'),
    path('addpdt/',views.addpdt,name='addpdt'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('product_update/',views.product_update,name='product_update'),
    path('s_login/',views.s_login,name='s_login'),
    path('s_register/',views.s_register,name='s_register'),
    path('s_masterpage/',views.s_masterpage,name='s_masterpage'),
    path('remove/<int:category_id>',views.remove,name='remove'),
    path('update/<int:pid>',views.product_update,name='product_update'),
    path('s_logout/',views.s_logout,name='s_logout')
]

seller/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.TextField(max_length=100,null=True)
    
    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.TextField(max_length=100,null=True)
    description=models.TextField(max_length=100,null=True)
    quantity=models.IntegerField(null=True)
    price=models.FloatField(null=True)
    image=models.ImageField(null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name
    
class Seller(models.Model):
    username=models.TextField(max_length=100,null=True)
    password=models.TextField(max_length=100,null=True)
    email=models.EmailField(null=True)

seller/views.py
from django.shortcuts import render ,redirect
from  seller.models import*
# Create your views here.
def s_index(request):
    return render(request,'seller/s_index.html')

def s_login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        try:
            seller=Seller.objects.get(username=username,password=password)
            request.session['seller']=seller.id
            return redirect('seller:s_index')
        except Seller.DoesNotExist:
            return render(request,'seller/s_login.html',{'msg':'invalid'})
    return render(request,'seller/s_login.html')

def s_logout(request):
    if 'seller' in request.session:
        del request.session['seller']
        return redirect('seller:s_login')
    else:
        return render(request,'seller/s_login.html')

def s_register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        email=request.POST['email']
        seller=Seller(username=username,password=password,email=email)
        seller.save()
    
    return render(request,'seller/s_register.html') 

def s_masterpage(request):
    
    return render(request,'seller/s_masterpage.html')

def addpdt(request):  
    cat=Category.objects.all()
    if request.method=='POST':
        name=request.POST['name']
        description=request.POST['description']
        quantity=request.POST['quantity']
        price=request.POST['price']
        image=request.FILES['image']
        
        category_id=request.POST.get('cat')
        category=Category.objects.get(id=category_id)
        pdt=Product(name=name,description=description,quantity=quantity,price=price,image=image,category=category)
        pdt.save()
    return render(request,'seller/addpdt.html',{'cat':cat})


def dashboard(request):
    pdt=Product.objects.all()
    return render(request,'seller/dashboard.html',{'product':pdt})

def remove(request,category_id):
    Product.objects.get(id=category_id).delete()
    return redirect('seller:dashboard')

def product_update(request,pid):
    cat=Category.objects.all()
    product=Product.objects.get(id=pid)
    if request.method=='POST':
        name=request.POST['name']
        description=request.POST['description']
        quantity=request.POST['quantity']
        price=request.POST['price']
        image=request.FILES['image']
        product.name=name
        product.description=description
        product.quantity=quantity
        product.price=price
        product.image=image

        product.save()
        return redirect('seller:dashboard')
    return render(request,'seller/product_update.html',{'i':product,
                                                        'cat':cat})
    





     

seller/templates/seller/addpdt.html
{% extends 'seller/s_masterpage.html' %}
{% load static %}
{% block content %}

<style>
    #addpdt_table{
        height: 450px;
        width: 400px;
        margin-left: 30px;
        text-align: center;
        
      
    }
    #addpdt_table h1{
        padding-left: -60px;
    }
    #addpdt_row{
        background-color: gray;
    }
    #div1{
        margin-top: 100px;
        margin-bottom: 100px;
        height: 550px;
        width: 400px;
        border-radius: 20px;
        background-image: url('https://i.pinimg.com/564x/30/28/7f/30287f2287b7471bc9582e5d6e49b05f.jpg');
        box-shadow: 20px 20px 10px black;
    }
    #input{
        color: black;
    }
    #addpdt_table th {
        text-align: left;
    }


</style>

<div class="row" id="addpdt_row">
    <div class="col-4"></div>
    <div class="div" id="div1">
        <div class="col-4">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table id="addpdt_table">
                <tr>
                    <th><h1 style="color: white;">Add Products</h1></th>
                </tr>
                <tr>
                    <th><label for="" style="text-align: left;">Product Name</label></th>
                </tr>
                <tr>
                    <th><input type="text" name="name" placeholder="Enter Name"></th>
                </tr>
                <tr>
                    <th><label for="">Description</label></th>
                </tr>
                <tr>
                   <th><input type="text" name="description" placeholder="Enter Description"></th>
                </tr>
               
                <tr>
                    <th><label for="">Quantity</label></th>
                </tr>
                <tr>
                    <th><input type="number" name="quantity" placeholder="Enter Quantity"></th>
                </tr>
                <tr>
                    <th><label for="">Price</label></th>
                </tr>
                <tr>
                    <th><input type="int" name="price" placeholder="Enter Price"></th>
                </tr>
                <tr>
                  <th><label for="">Image</label></th>
                </tr>
                <tr>
                    <th><input type="file" name="image" placeholder="Add Image" id="input"></th>
                </tr>
                <tr><th><label for="">Select Category</label></th></tr>
                <tr>
                    <th><select name="cat" id="">
                        {% for i in cat %}
                        <option value="{{i.id}}" 
                        name="">{{i.name}}</option>
                        {% endfor %}
                    </select></th>
                </tr>
                <tr>
                    <th><button type="submit" id="subbtn" style="background-color: rgb(75, 74, 74); border-radius: 5px; text-decoration: none; margin-top: 20px; color: white;">submit</button></th>
                </tr>
        
            </table>

        </form>   
        </div>
    </div>
    <div class="col-4"></div>
</div>





























{% endblock %}

seller/templates/seller/dashboard.html
{% extends 'seller/s_masterpage.html' %}
{% load static %}
{% block content %}

<style>
    #dashtable{
    
        border: 2px solid black;
        text-align: center;
        width: 1200px;
        margin-top: 50px;
        margin-bottom: 50px;
        margin-left: 80px;
        font-size: large;
        font-weight: 500;
        color: white;
        
    }
    #dashtable  th {
        border: 1px solid black;
        width: 150px;
        height: 50px;
    }
    img{
        height: 150px;
        width: 150px;
    }
    #dashtable td{
        border: 1px solid black;

    }
    

</style>




<div class="row" style="background-image: url('https://i.pinimg.com/564x/28/6c/9b/286c9bf42516e21c9c87e360ac2441ee.jpg');">
    <div class="col-12">
        
        <table id="dashtable">
            <tr>
                <th>Product Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Image</th>
                <th>Update</th>
                <th>Remove</th>
            </tr>
{% for i in product %}
            
            <tr>
                
                <td>{{i.name}}</td>
                <td>{{i.description}}</td>
                <td>{{i.category}}</td>
                <td>{{i.quantity}}</td>
                <td>{{i.price}}</td>
                <td><img src="{{i.image.url}}" alt=""></td>
                <td><a href="{% url 'seller:product_update' i.id %}" style="text-decoration: none; color:white;"><i class="fa-solid fa-pen"></i></a></td>
                <td><a href="{% url 'seller:remove' i.id %}" style="color: white;"><i class="fa-solid fa-trash"></i></a></td>
                
            </tr>
            
{% endfor %}
        </table>
       
    </div>
   

</div>



















{% endblock %}

seller/templates/seller/product_update.html
{% extends 'seller/s_masterpage.html' %}
{% load static %}
{% block content %}




<style>
    #addpdt_table{
        height: 450px;
        width: 400px;
        margin-left: 30px;
        text-align: center;
       
    }
    #addpdt_table h1{
        padding-left: -60px;
    }
    #addpdt_row{
       
        background-image: url('https://wallpaperset.com/w/full/0/5/9/156333.jpg');
        background-size: cover;
    }
    #div1{
        height: 550px;
        width: 400px;
        color: white;
        border-radius: 20px;
        background-image: url('https://t4.ftcdn.net/jpg/02/68/80/71/360_F_268807166_oPVMMlJcxy4OjBDkl9JPxqfJeMC98yNm.jpg');
        margin-top: 100px;
        margin-bottom: 100px;
        border: 1px solid red;
        margin-left: -200px;
        box-shadow: 20px 20px 10px black;
    }
    #input{
        color: black;
    }
    #addpdt_table th {
        text-align: left;
    }

</style>

<div class="row" id="addpdt_row">
    <div class="col-4"></div>
    <div class="div" id="div1">
        <div class="col-4">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <table id="addpdt_table">
                <tr>
                    <th><h1>Update Product</h1></th>
                </tr>
                <tr>
                    <th><label for="" style="text-align: left;">Product Name</label></th>
                </tr>
                <tr>
                    <th><input type="text" value="{{i.name}}" name="name" placeholder="Enter Name"></th>
                </tr>
                <tr>
                    <th><label for="">Description</label></th>
                </tr>
                <tr>
                   <th><input type="text" value="{{i.description}}" name="description" placeholder="Enter Description"></th>
                </tr>
               
                <tr>
                    <th><label for="">Quantity</label></th>
                </tr>
                <tr>
                    <th><input type="number" value="{{i.quantity}}" name="quantity" placeholder="Enter Quantity"></th>
                </tr>
                <tr>
                    <th><label for="">Price</label></th>
                </tr>
                <tr>
                    <th><input type="int" value="{{i.price}}" name="price" placeholder="Enter Price"></th>
                </tr>
                <tr>
                  <th><label for="">Image</label></th>
                </tr>
                <tr>
                    <th><input type="file" value="{{i.image}}" name="image" placeholder="Add Image" id="input"></th>
                </tr>
                <tr><th><label for="">Select Category</label></th></tr>
                <tr>
                    <th><select name="cat" id="">
                        {% for i in cat %}
                        <option value="{{i.id}}" 
                        name="">{{i.name}}</option>
                        {% endfor %}
                    </select></th>
                </tr>
                <tr>
                    <th><button type="submit">submit</button></th>
                </tr>
        
            </table>
           
        </form>   
        </div>
    </div>
    <div class="col-4"></div>
</div>



























{% endblock %}

seller/templates/seller/s_index.html
{% extends 'seller/s_masterpage.html' %}
{% load static %}
{% block content %}

<style>
    .col-12{
        background-image: url('');
        height: 300px;
    }
    .row .col-12 h1{
        color: black;
        margin-right: 400px;
    
    }
    #img{
        /* margin-left: 10px; */
        float: left;
    }



</style>



<div class="row">
    <div class="col-6">
        <img src="https://img.freepik.com/free-photo/photocomposition-horizontal-shopping-banner-with-woman-big-smartphone_23-2151201773.jpg?w=740&t=st=1710144074~exp=1710144674~hmac=d2869f105de08c90b54e9c5bbd30d83f8d82acdff736353521215e9c45a11600">
    </div>
    <div class="col-6" style="background-image: url('https://img.freepik.com/free-photo/black-friday-elements-assortment_23-2149074076.jpg?w=740&t=st=1710144138~exp=1710144738~hmac=a4e2db8b9bdf1f47121d44fcaf823569fb73e5be5c360d09154e99666f10d81b');">
        <!-- <img src="https://img.freepik.com/free-photo/black-friday-elements-assortment_23-2149074076.jpg?w=740&t=st=1710144138~exp=1710144738~hmac=a4e2db8b9bdf1f47121d44fcaf823569fb73e5be5c360d09154e99666f10d81b"> -->
        <h2 style="margin-top: 30px; margin-left: 20px;"><b>LIMITED TIME OFFER</b></h2><br>
            <h3 style="margin-left: 20px;">Become an Easyshope seller <br>
            Start your selling journey on <br> Easyshope and become a <br>part of our 14 Lakh+ <br> seller community</h3>

    </div>
</div>
<div class="row">
    <!-- <div class="col-12">
        <h1>Become a Easyshope Seller <br> and sell to 45+Crore customers
        </h1>
    </div> -->
</div>
<div class="row">
    <div class="col-6"><h1><b>Why do sellers love selling on Easyshope</b></h1>
        <h3>45 crore+ customers across India trust Easyshope.com to be their number 1 online shopping destination. It is no surprise that more than a million sellers trust their products to be made available 24x7 on Easyshope.
            <br>
            <h1><b>Opportunity</b></h1> <br>

           <h3> 45 crore+ of customers across 19000+ pincodes, and access to shopping festivals like The Big Billion Days, and more.
            Ease of Doing Business icon
            Ease of Doing Business
            Create your Easyshope seller account in under 10 minutes with just 1 product and a valid GSTIN number.</h3>
            <br>
            <h1><b>Growth</b></h1>
            <br>
            <h3> see an average 2.8X spike in growth, 2.3X more visibility, and up to 5X growth in The Big Billion Days Sale.</h3>
            <br>
            <h1><b>Additional Support</b></h1>
            <br>
            <h3>Account management services, exclusive training programs, business insights, catalogue/photoshoot support, and more.</h3>
    </div>
    <div class="col-2">
        
    </div>
    <div class="col-4">
        <img src="{% static 'images/sellerimg.jpg' %}" alt="" style="width: 400px; height: 400px;">
        <h1> Why sellers choose Easyshope ?</h1> <br>
            <ul>
                <li>
                    <p>
                        <h4>Crores of customers</h4>
                        <b>
                            Reach crores of customers on Easyshope.in, India's most visited shopping destination.</b>
                    </p>
                </li>
                <li>
                    <p><h4>5.1K+ </h4>
                        <b>
                        sellers became crorepatis in 2022. You could be next.</b></p>
                </li>
                <li>
                    <p>
                        <h4>Unbeatable reach</h4>
                       <b> 
                        Deliver to 100% of India's serviceable pincodes, through Easy Ship & Fulfillment by Easyshope.</b>
                    </p>

                </li>
                <li>
                    <h4>Secure timely payments</h4>
                  <b>Funds are deposited directly to your bank account every 7 days, including for Pay on Delivery order.</b>
                </li>
                <li>
                    <h4>Ease of starting</h4>
                    <b>From product photography to hassle free delivery & returns management, Amazon has a solution for you.</b>
                </li>
                <li>
                    <h4>Sell to customers worldwide</h4>
                    <b>Sign up for Amazon Global Selling & reach customers in upto 200+ countries.</b>
                </li>
            </ul>
            <br>
      
        
    </div>
</div>
<div class="row" style="margin-top: 50px; margin-bottom: 70px;">
    <h1 style="margin-bottom: 50px;"><b>How to sell on Easyshope</b></h1>
  <div class="col-3"><h3><b>STEP 1: Register your account</b></h3>
    <b>Register on Amazon with GST/PAN details and an active bank account</b>
  </div>
  <div class="col-3">
    <h3><b>STEP 2: Choose storage & shipping</b></h3>
    <b>Choose storage, packaging, and delivery options</b>
  </div>
  <div class="col-3"><h3><b>STEP 3: List your products</b></h3>
    <b>List your products by providing product and brand details</b>
  </div>
  <div class="col-3">
    <h3><b>STEP 4: Complete orders & get paid</b></h3>
    <b>Deliver orders to customers on time and get paid within 7 days of delivery</b>
  </div>
</div>




















{% endblock %}

seller/templates/seller/s_login.html
{% extends 'seller/s_masterpage.html' %}
{% load static %}
{% block content %}

<style>
    #seller_table{
        height: 400px;
        width: 400px;
        margin-left: 500px;
        color: white;
        /* border: 1px solid black; */
        background-image: url('https://i.pinimg.com/564x/e7/25/92/e72592a35cccdb247afd8e495e90458c.jpg');
        border-radius: 10px;
        margin-top: 100px;
        margin-bottom: 100px;
        box-shadow: 20px 20px 10px black;

    }
    input{
        width: 350px;
        margin-left: 30px;
    }
    label{
        margin-left: 30px;
    }
    #logintable{
        
        background-color: rgb(241, 148, 7);
        

    }
    #btn{
        text-decoration: none;
        width: 70px;
        color: white;
        background-color: rgba(223, 74, 15, 0.849);
        border-radius: 5px;
        margin-left: 165px;
    }
    #loginbtn{
        height: 50px;
    }
    #btn:hover{
        background-color: rgba(233, 114, 16, 0.164);

    }
    #para,#para2{
        margin-left: 30px;
    }
    #signup{
        text-decoration: none;
        border-radius: 5px;
        width: 80px;
        margin-left: 160px;
        margin-bottom: 50px;
        background-color: rgba(216, 170, 21, 0.973);
        color: white;
    }
    #signup:hover{
        background-color: rgba(19, 19, 167, 0.048);
        
    }
    #parasign{
        margin-left: 140px;
        margin-top: 30px;
    }
    #msg{
        padding-left: 40px;
        color: red;
    }



</style>

<div class="row" id="logintable">
    <form action="" method="post" onsubmit="return login()">
        {% csrf_token %}
        <table id="seller_table">
            <tr>
                <th><h1>Login</h1></th>
            </tr>
            <tr>
                <td><label for="username" id="username" >Username</label></td>
            </tr>
            <tr>
                <td><input type="text" name="username" placeholder="Type your username" id="user"><br><p id="para" style="color: red;"></p></td>
                
            </tr>
            <tr>
                <td><label for="password" id="password">Password</label></td>
            </tr>
            <tr>
                <td><input type="password" name="password" placeholder="Type your password" id="password1"><br><p id="para2" style="color: red;"></p><p id="msg">{{msg}}</p></td>
                
            </tr>
            <tr>
                <td id="loginbtn"><button type="submit" id="btn">Login</button></td> 
            </tr>
            <tr>
                <td><p id="parasign"> Or Sign Up using</p><button id="signup"> <a href="{% url 'seller:s_register' %}">Sign Up</a> </button></td>

            <tr>
                
            </tr>
        </table>
    </form>



    <script>
        function login(){
           
            user=document.getElementById('user').value
            psd=document.getElementById('password1').value
            if(user==''){
                document.getElementById('para').innerHTML='Please enter username'
                return false
            }else if(psd==''){
                
                document.getElementById('para2').innerHTML='Please enter password'
                return false
            }return true
        }

    </script>

</div>

{% endblock %}

seller/templates/seller/s_masterpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'styles/masterpage.css' %}">
    <link rel="stylesheet" href="{% static 'styles/contact.css' %}">
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
    <link rel="stylesheet" href="">

    <style>

#logo{
    width: 250px;
    height: 100px;
}
#row1{
    background-color: #ca2f0d;
    height: 100px;
}
#table1{
    margin-left: 250px;
    font-weight: 500px;
    margin-top: 25px;
    font-size: large;
    font-weight: 500;
    text-align: center;
    width: 600px;

}
#table1 td{
    width: 150px;
   
}
#table1 button {
    text-decoration: none;
    border: none;
    border-radius: 5px;
    background-color:#ca2f0d ;
}
button a{
    text-decoration: none;
    color: white;
}
#table1 button:hover{
    background-color:#141111;
}


#row2 {
    background-color: #141111;
    color: white;
    height: 280px;
    padding-top: 25px;

}
#row2 button{
    margin-left: 100px;
    margin-top: 10px;
    background-color: white;
}
#row2 button:hover{
    background-color: #5D6D7E;
}
.fa-brands{
    width: 30px;
}
#media{
    padding-left: 150px;
}
.fa-solid{
    width: 30px;
    height: 20px;
    
}
#more{
    padding-left: 60px;
}
input{
    border-radius: 10px;
}
   </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body>
    <div class="conatiner">
        <div class="row" id="row1">
            <div class="col-4"><img src="{% static 'images/logo.png' %}" alt="" id="logo">
            </div>
            <div class="col-8">
                <table id="table1" >
                    <tr>
                          <td><button><a href="{% url 'seller:s_index' %}">Home</a></button></td>
                          <td><button><a href="{% url 'seller:addpdt' %}">Add Product</a></button></td>
                          <td><button><a href="{% url 'seller:dashboard' %}">View Product</a></button></td>
                          <td><button><a href="{% url 'seller:s_login' %}">Login</a></button></td>
                          <td style="text-align: left;"><button><a href="{% url 'seller:s_logout' %}">Logout</a></button></td>


                    </tr>
                </table>
            </div>
        </div>
        


    {% block content %}
       
    {% endblock %}
    <div class="row" id="row2">
        <div class="col-4" id="more">

            <p><span><b>About Company</b></span> <br>Easyshope is an online shopping platform owned by the Indian company Fashnear Technologies Private Limited.It is an online marketplace that facilitates trade between suppliers, resellers and customers, with heavy reliance of external social media platforms such as Facebook and Instagram.
               <br> <button style="width: 70px; height: 30px; background-color: black; border-radius: 10px; "><a href="{% url 'customer:about' %}">More</a></button>
            </p>
        </div>
        <div class="col-4" id="media">
            <table >
                <tr>
                    <th><b>Keep Connected</b></th>
                </tr>
                <tr><td><i class="fa-brands fa-facebook"></i>Like in Facebook</td></tr>
                <tr><td><i class="fa-brands fa-x-twitter"></i>Follow in X</td></tr>
                <tr><td><i class="fa-brands fa-instagram"></i>Like in Instagram</td></tr>
                <tr><td><i class="fa-brands fa-pinterest"></i>Follow in Pinterest</td></tr>
                <tr><td><i class="fa-brands fa-youtube"></i>Subscribe in Youtube</td></tr>
            </table>
        </div>
        <div class="col-4">
        <table id="table3">
            <p><b>Contact Us</b></p>
            <tr><td><i class="fa-solid fa-house"></i></td><td>No. 78/9,Outer Ring Road, Bellandur,<br> Varthur Hobli, Bengaluru, India</td></tr>
            <tr><td><i class="fa-solid fa-mobile"></i></td><td>+91-6863219608</td></tr>
            <tr><td><i class="fa-solid fa-envelope"></i></td><td>easyshope@gmail.com</td></tr>
        </table>
        </div>
    </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script></body>
</html>

seller/templates/seller/s_register.html
{% extends 'seller/s_masterpage.html' %}
{% load static %}
{% block content %}

<style>
    #register_row{
        /* border: 1px solid black; */
       
        background-color:rgb(252, 150, 167);
    }
    #register_table{
        /* border: 1px solid black; */
        margin-left: 500px;
        background-image: url('https://i.pinimg.com/564x/94/b7/7b/94b77b22988e58089fbc7d864e01caf1.jpg');
        color:black;
        width: 400px;
        border-radius: 10px;
        margin-bottom: 50px;
        margin-top: 40px;
        box-shadow: 20px 20px 10px;
        
    }
    input{
        width: 300px;
        margin-left: 50px;
    }
    label{
        margin-left: 50px;
    }
    #registerbtn{
        margin-left: 150px;
        border-radius: 10px;
        background-color: black;
        color: white;
        text-decoration: none;
        margin-bottom: 10px;
    }
    #registerbtn:hover{
        color: black;
        background-color: white;
    }
    #loginbtn{
        padding-left: 75px;
    }
    #loginbtn a{
        color:black;
    }
    #loginbtn a:hover{
        color: red;
    }
    #para1, #para2, #para3, #para4{
        margin-left: 50px;
        color: red;
    }

</style>

<div class="row" id="register_row">
        <form action="" method="post" onsubmit="return register()">
            {% csrf_token %}
            <table id="register_table">
                <tr>
                    <td><h1>Register</h1></td>
                </tr>
                <tr>
                    <td><label for="">Username</label></td><br>
                </tr>
                <tr>
                    <td><input type="text" name="username" placeholder="Enter username" id="user"><br><p id="para1"></p></td>
                </tr>
                <tr>
                    <td><label for="email">Email</label></td>
                </tr>
                <tr>
                    <td><input type="email" name="email" placeholder="Enter email" id="email"><br><p id="para2"></p></td>
                </tr>
                <tr>
                    <td><label for="password">Password</label></td>
                </tr>
                <tr>
                    <td><input type="password" name="password" placeholder="Enter Password" id="psd"><br><p id="para3"></p></td>
                </tr>
                <tr>
                    <td><label for=""></label>Repeat Password</td>
                </tr>
                <tr>
                    <td><input type="password"  placeholder="Repeat Password" id="repeat"><br><p id="para4"></p><p id="para4"></p></td>
                </tr>
                <tr>
                    <td><button id="registerbtn" type="submit">Register</button></td>
                </tr>
                <tr>
                    <td id="loginbtn">Already have an account? <a href="{% url 'seller:s_login' %}">Login</a></td>
                </tr>
    
            </table>
    </form>
</div>

<script>
    function  register(){
        user=document.getElementById('user').value
        email=document.getElementById('email').value
        pass=document.getElementById('psd').value
        pass2=document.getElementById('repeat').value

        if(user==''){
            document.getElementById('para1').innerHTML='Please enter username'
            return false
        }else if(email==''){
            document.getElementById('para2').innerHTML='please enter email'
            return false
        }else if(pass==''){
            document.getElementById('para3').innerHTML='please enter password'
            return false
        }else if(pass.length<6){
            document.getElementById('para3').innerHTML='please enter above 6 characters'
            return false
        }else if(pass2==''){
            document.getElementById('para4').innerHTML='please repeat password'
            return false
        }else if(pass!=pass2){
            document.getElementById('para4').innerHTML='both password must be same'
            return false
        }else{
            
        }return true
    }
    

</script>





























{% endblock %}