customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('masterpage/',views.masterpage,name='masterpage'),
    path('men/',views.men,name='men'),
    path('women/',views.women,name='women'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('logout/',views.logout,name='logout'),
    path('payment/',views.payment,name='payment'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart,name='cart'),
    path('remove_from_cart/<int:product_id>/',views.remove_from_cart,name='remove_from_cart'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:products_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:products_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('masterpage1/',views.masterpage1,name='masterpage1'),
    path('profile/',views.profile,name='profile')





]

easy_shope/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views 
app_name='seller'
urlpatterns=[
    path('s_index/',views.s_index,name='s_index'),
    path('addpdt/',views.addpdt,name='addpdt'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('product_update/',views.product_update,name='product_update'),
    path('s_login/',views.s_login,name='s_login'),
    path('s_register/',views.s_register,name='s_register'),
    path('s_masterpage/',views.s_masterpage,name='s_masterpage'),
    path('remove/<int:category_id>',views.remove,name='remove'),
    path('update/<int:pid>',views.product_update,name='product_update'),
    path('s_logout/',views.s_logout,name='s_logout')
]

customer/models.py
from django.db import models
from .models import *
from seller .models import *
# Create your models here.
class Customer(models.Model):
    username=models.TextField(max_length=100,null=True)
    password=models.TextField(max_length=100,null=True)
    email=models.EmailField(null=True)

class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveBigIntegerField(default=1)

class Wishlist(models.Model):
    customers=models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    products=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)

   
    

customer/views.py
from django.shortcuts import render ,redirect
from seller.models import *
from .models import * 
from django.http import HttpResponse

# Create your views here.
def index(request):
   if 'customer' in request.session:
    cust_id=request.session.get('customer')
    cust=Customer.objects.get(id=cust_id)
    a=cust.username
    cust=a[0]
    return render(request,'index.html',{'customer':cust})
   else:
    return render(request,'index.html')


def login(request):
    if request.method=='POST':
       email=request.POST['email']
       password=request.POST['password']
       try:
         cust=Customer.objects.get(email=email,password=password)
         request.session['customer']=cust.id
         return redirect('customer:index')
       except Customer.DoesNotExist:    
         return render(request,'login.html',{'msg':'invalid'})
    return render(request,'login.html')

def logout(request):
   if 'customer' in request.session:
      del request.session['customer']
      return redirect('customer:login')
   else:
      return render(request,'login.html')
   
def register(request):
    if request.method=='POST':
       username=request.POST['username']
       password=request.POST['password']
       email=request.POST['email']
       cust=Customer(username=username,password=password,email=email)
       cust.save()
       return redirect('customer:login')
    return render(request,'register.html')

def masterpage(request):
    return render(request,'masterpage.html')

def masterpage1(request):
    return render(request,'masterpage1.html')

def men(request):
   if 'customer' in request.session:
    cat=Category.objects.get(name='men')
    pdt=Product.objects.filter(category=cat)
    return render(request,'men.html',{'products':pdt})
   else:
      return redirect('customer:login')

def women(request):
   if 'customer' in request.session:
    cat=Category.objects.get(name='women')
    pdt=Product.objects.filter(category=cat)
    return render(request,'women.html',{'products':pdt})
   else:
      return redirect('customer:login')
    

def contact(request):
    return render(request,'contact.html')

def about(request):
    return render(request,'about.html')

def cart(request):
   if 'customer' in request.session:
    cart_items=Cart.objects.all()
    total_price=sum(item.product.price*item.quantity for item in cart_items)
    total_price_per_item=[]
    grand_total=0
    for item in cart_items:
      item_total=item.product.price*item.quantity
      total_price_per_item.append({'item':item,'total':'item_total'})
      grand_total+=item_total    
    return render(request,'cart.html',{'cart_items':cart_items,'grand_total':grand_total,'total_price':total_price})
   else:
      return redirect('customer:login')

def add_to_cart(request,product_id):
   if request.method=='POST':
      product=Product.objects.get(id=product_id)
      cart_item,created=Cart.objects.get_or_create(product=product)
      if not created:
         cart_item.quantity+=1
         cart_item.save()
   return redirect('customer:cart')

def remove_from_cart(request,product_id):
   product=Product.objects.get(id=product_id)
   cart_item=Cart.objects.get(product=product)
   cart_item.delete()
   return redirect('customer:cart')


def payment(request):
   return render(request,'payment.html')

def wishlist(request):
   wishlist_item=Wishlist.objects.all()
   return render(request,'wishlist.html',{'wishlist_item':wishlist_item})


def add_to_wishlist(request,products_id):
   if request.method=='POST':
      pdt=Product.objects.get(id=products_id)
      wishlist,created=Wishlist.objects.get_or_create(products=pdt)
      wishlist.save()
      return redirect('customer:wishlist')
   

def remove_from_wishlist(request,products_id):
   product=Product.objects.get(id=products_id)
   wishlist_item=Wishlist.objects.get(products=product)
   wishlist_item.delete()
   return redirect('customer:wishlist')

def profile(request):
   if 'customer' in request.session:
    cust_id=request.session.get('customer') 
    cust=Customer.objects.get(id=cust_id)
        
    return render(request,'profile.html',{'customer':cust})
   else:
      return redirect('customer:login')

customer/templates/cart.html
{% extends 'masterpage1.html' %}
{% load static %}
{% block content %}

<style>
    #cart_table{
        width: 1100px;
        margin-left: -70px;
        font-size: large;
        text-align: center;
        margin-bottom: 50px;

        /* border: 1px solid black; */
        

    }

    #cart_table th {
        height: 50px;
        font-size: large;
        /* border: 1px solid black; */
    }
    img{
        height: 200px;
        width: 150px;
        
        
    }
    #ppbtn{
        background-image: linear-gradient(#0dccea, #0d70ea);
        border: 0;
        border-radius: 4px;
        box-shadow: rgba(0, 0, 0, .3) 0 5px 15px;
        box-sizing: border-box;
        color: #fff;
        cursor: pointer;
        font-family: Montserrat,sans-serif;
        font-size: .9em;
        margin: 5px;
        padding: 10px 15px;
        text-align: center;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
    }
    

</style>

<div class="container-fluid">
    <div class="row"  style=" background-color:rgb(159, 223, 185)">
        <h1 style="margin-top: 20px;margin-bottom: 30px; padding-left: 600px;">Shopping Cart</h1>
    </div>
    
    <div class="row"style=" background-color:rgb(159, 223, 185)">
        <div class="col-1">
    
        </div>
        <div class="col-10">
            <table id="cart_table">
                <tr>
                    <th style="width: 300px;">Product</th>
                    <th style="width: 300px;">Product Name</th>
                    
                    <th style="width: 200px;">Price</th>
                    <th style="width: 200px;;">Quantity</th>
                    <th style="width: 200px;">Subtotal</th>
                    <th style="width: 200px;">Remove</th>
                    
                </tr>
                {% for item in cart_items %}
                <tr>
                    <td><img src="{{item.product.image.url}}" alt=""></td>
                    <td><b>{{item.product.name}}</b></td>
                    <td>{{item.product.price}}</td>
                    <td>{{item.quantity}}</td>
                    <td>$125.89</td>
                    <td><a href="{% url 'customer:remove_from_cart' item.product.id %}">Remove</a></td>
                </tr>
                {% endfor %}
                <!-- <tr>
                    <th>Promotion Code</th>
                    <td></td>
                    <td><b>Cart Totals</b></td>
                </tr>
                <tr>
                    <td>
                        <input type="text" placeholder="Coupon Code">
                        <button type="submit" style="background-color: blue; border-radius: 20px; color: white;">Apply Coupon</button>
                    </td><td></td>
                    <td><b>Subtotal</b></td>
                    <td>$125.435</td>
                </tr> -->
                <tr>
                    <td></td><td></td>
                    <td><b>Total</b></td>
                    <td><b>{{grand_total}}</b></td>
                    <td><button type="submit" id="ppbtn" style="margin-top: 30px; border-radius: 20px; background-color: blue; color: white;"> <a href="{% url 'customer:payment' %}">Buy Now</a></button></td>
                </tr>
            </table>
    
        </div>
        <div class="col-1" >
    
        </div>
    </div>
    
</div>





























{% endblock %}

customer/templates/masterpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'styles/masterpage.css' %}">
    <link rel="stylesheet" href="{% static 'styles/contact.css' %}">
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">

    <style>

#logo{
    width: 250px;
    height: 100px;
    /* border: 1px solid black; */

    
}
#row1{
    background-color: #ca2f0d;
    height: 100px;
    /* border: 1px solid black; */

}
#table1{
    margin-left: 270px;
    font-weight: 500px;
    margin-top: 25px;
    font-size: large;
    font-weight: 500;
    /* border: 1px solid black; */
    text-align: center;

    

}
#table1 td{
    width: 150px;
    /* border: 1px solid black; */

   
}
#table1 button {
    text-decoration: none;
    border: none;
    border-radius: 5px;
    background-color:#ca2f0d ;
    /* border: 1px solid black; */

}
button a{
    text-decoration: none;
    color: white;
}
#table1 button:hover{
    background-color:#141111;
}

#row2 {
    background-color: #141111;
    color: white;
    height: 280px;
    padding-top: 25px; 
    width: 1240px;
    /* border: 1px solid rgb(233, 21, 21); */

    
}
#row2 button{
    margin-left: 100px;
    margin-top: 10px;
    background-color: white;
    /* border: 1px solid black; */

} 
 #row2 button:hover{
    background-color: #5D6D7E;
}
.fa-brands{
    width: 30px;
}
#media{
    padding-left: 150px;
}
.fa-solid{
    width: 30px;
    height: 20px;
    
}
#more{
    padding-left: 60px;
}
#moreabout a{
    background-color: #141111;
    width: 40px;

}
#moreabout:hover{
    transform: scale(1.1)translate(2px);
    transition: .2s;

}


   </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container-fluid">
        <div class="row" id="row1">
            <div class="col-4"><img src="{% static 'images/logo.png' %}" alt="" id="logo">
            </div>
            <div class="col-8">
                <table id="table1">
                    <tr>
                        <td><button><a href="{% url 'customer:women' %}">Home</a></button></td>
                        <td><div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Shope
                            </button>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'customer:men' %}">Men</a></li>
                              <li><a class="dropdown-item" href="{% url 'customer:women' %}">Women</a></li>
                            </ul>
                          </div></td>
                          <td><button><a href="{% url 'customer:contact' %}">Contact</a></button></td>
                          <td><button><a href="{% url 'customer:about' %}">About</a></button></td>
                          <td><button><a href="{% url 'customer:login' %}">Login</a></button></td>
                          <td><button><a href="{% url 'customer:logout' %}">Logout</a></button></td>

                    </tr>
                </table>
            </div>
        </div>
        


    {% block content %}
       
    {% endblock %}
    
    <div class="row" id="row2">
        <div class="col-4" id="more">

            <p><span><b>About Company</b></span> <br>Easyshope is an online shopping platform owned by the Indian company Fashnear Technologies Private Limited.It is an online marketplace that facilitates trade between suppliers, resellers and customers, with heavy reliance of external social media platforms such as Facebook and Instagram.
               <br> <button id="moreabout" style="width: 70px; height: 30px; background-color: black; border-radius: 10px;"><a href="{% url 'customer:about' %}"><b>More</b></a>
            </p>
        </div>
        <div class="col-4" id="media">
            <table >
                <tr>
                    <th><b>Keep Connected</b></th>
                </tr>
                <tr><td><i class="fa-brands fa-facebook"></i>Like in Facebook</td></tr>
                <tr><td><i class="fa-brands fa-x-twitter"></i>Follow in X</td></tr>
                <tr><td><i class="fa-brands fa-instagram"></i>Like in Instagram</td></tr>
                <tr><td><i class="fa-brands fa-pinterest"></i>Follow in Pinterest</td></tr>
                <tr><td><i class="fa-brands fa-youtube"></i>Subscribe in Youtube</td></tr>
            </table>
        </div>
        <div class="col-4">
        <table id="table3">
            <p><b>Contact Us</b></p>
            <tr><td><i class="fa-solid fa-house"></i></td><td>No. 78/9,Outer Ring Road, Bellandur,<br> Varthur Hobli, Bengaluru, India</td></tr>
            <tr><td><i class="fa-solid fa-mobile"></i></td><td>+91-6863219608</td></tr>
            <tr><td><i class="fa-solid fa-envelope"></i></td><td>easyshope@gmail.com</td></tr>
        </table>
        </div>
    </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

customer/templates/masterpage1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
    #logo{
    width: 220px;
    height: 150px;
    margin-bottom: 10px;
    padding-bottom: 50px;
    /* border: 1px solid black; */
    }
    #row1{
    background-color: #ca2f0d;
    height: 100px;
    }
    #table1{
    margin-left: 270px;
    font-weight: 500px;
    margin-top: 25px;
    font-size: large;
    font-weight: 500;
    /* border: 1px solid black; */
    text-align: center;
    }
    #table1 td{
    width: 150px;
    /* border: 1px solid black; */
    }
    #table1 button {
    text-decoration: none;
    border: none;
    border-radius: 5px;
    background-color:#ca2f0d ;
    /* border: 1px solid black; */
    }
    button a{
    text-decoration: none;
    color: white;
    }
    #table1 button:hover{
    background-color:#141111;
    }
    #keepconnected td {
        height: 30px;
        width: 140px;

    }
    #table3 td{
        width: 70px;
        height:35px;
    /* border: 1px solid black; */

    }
    #table3{
        width: 370px;
        color: white;
    }
    #footer{
        background-color: black;
        color: white;

    }
    #moreabout a{
    background-color: #141111;
    width: 40px;

    }
    #moreabout:hover{
    transform: scale(1.1)translate(2px);
    transition: .2s;

    }
    


    </style>

</head>
<body>
    <div class="container-fluid">
        <div class="row" id="row1">
            <div class="col-4">
                <img src="{% static 'images/logo.png' %}" alt="" id="logo">
            </div>
            <div class="col-8">
                <table id="table1">
                    <tr>
                        <td><button><a href="{% url 'customer:index' %}">Home</a></button></td>
                        <td><div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Shop
                            </button>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'customer:men' %}">Men</a></li>
                              <li><a class="dropdown-item" href="{% url 'customer:women' %}">Women</a></li>
                            </ul>
                          </div></td>
                          <td><button><a href="{% url 'customer:contact' %}">Contact</a></button></td>
                          <td><button><a href="{% url 'customer:about' %}">About</a></button></td>
                          <td><button><a href="{% url 'customer:login' %}">Login</a></button></td>
                          <td><button><a href="{% url 'customer:logout' %}">Logout</a></button></td>
                          <td><a href="{% url 'customer:profile' %}"><i class="fa-regular fa-user" style="color: white;"></i></a></td>
                    </tr>
                </table>
            </div>
        </div>

    </div>

    {% block content %}

    {% endblock %}

    <div class="container-fluid">
        <div class="row" id="footer">
            <div class="col-4" style=" margin-top: 20px;"><h5 style="margin-left: 110px;"><b>About Company</b></h5></p>Easyshope is an online shopping platform owned by the Indian company Fashnear 
                Technologies Private Limited.It is an online marketplace that facilitates trade between suppliers, 
                resellers and customers, with heavy reliance of external social media platforms such as Facebook and Instagram.
                <br><button id="moreabout" style="width: 70px; height: 30px; background-color: black; border-radius: 10px;"><a href="{% url 'customer:about' %}">More</a></button>
            </div>
            <div class="col-4" style=" margin-top: 20px;">
                <table id="keepconnected">
                    <h5 style="margin-left: 110px;"><b>Keep connected</b></h5></p>
                    <tr><td style="text-align:center;"><i class="fa-brands fa-facebook"></i></td><td>Like in Facebook</td></tr>
                    <tr><td style="text-align:center;"><i class="fa-brands fa-x-twitter"></i></td><td>Follow in X</td></tr>
                    <tr><td style="text-align:center;"><i class="fa-brands fa-instagram"></i></td><td>Like in Instagram</td></tr>
                    <tr><td style="text-align:center;"><i class="fa-brands fa-pinterest"></i></td><td>Follow in Pinterest</td></tr>
                    <tr><td style="text-align:center;"><i class="fa-brands fa-youtube"></i></td><td>Subscribe in Youtube</td></tr>
                </table>
            </div>
            <div class="col-4" style="margin-top: 20px;">
                <table id="table3">
                    <h5 style="margin-left: 110px;"><b>Contact Us</b></h5></p>
                    <tr><td style="text-align:center;" ><i class="fa-solid fa-house"></i></td><td>No. 78/9,Outer Ring Road, Bellandur,<br>
                         Varthur Hobli, Bengaluru, India</td></tr>
                    <tr><td  style="text-align:center;"><i class="fa-solid fa-mobile"></i></td><td>+91-6863219608</td></tr>
                    <tr><td  style="text-align:center;"><i class="fa-solid fa-envelope"></i></td><td>easyshope@gmail.com</td></tr>
                    <tr><td  style="text-align:center;"><i class="fa-brands fa-firefox-browser"></i></td><td>www.easyshope.com</td></tr>
                </table>
            </div>
        </div>
    </div>
    

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

customer/templates/men.html
{% extends 'masterpage1.html' %}
{% load static %}
{% block content %}

<style>
  #love{
    text-decoration: none;
    font-size: x-large;
  }
  #love:hover{
    background-color: red;
  }
  #lovebtbn{
    margin-left: 50px;
  }
  #lovebtn2{
    text-decoration: none;
    border: none;
    background-color: white;
  }
</style>

<div class="container-fluid">
  <div class="row" style="text-align: center;">
    <h1 style="color: #B40431;">𝙻𝚎𝚝'𝚜 𝙴𝚡𝚙𝚕𝚘𝚛𝚎 Men's 𝚆𝚎𝚊𝚛</h1>
</div>


<div class="row" style="margin-bottom: 100px;">
  {% for i in products %}
    <div class="col-3">
        <div class="card" style="width: 18rem; margin-top: 50px">
        <img src="{{i.image.url}}" class="card-img-top" alt="..."  style="height: 450px;">
        <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">57% off <h4>Rs {{i.price}}</h4> </p> 

          <form action="{% url 'customer:add_to_wishlist' i.id %}" method="post">
            {% csrf_token %}
            <button type="submit" id="lovebtn2"><p id="lovebtn"><i class="fa-regular fa-heart" id="love"></i></p></button>
          </form>

          <form action="{% url 'customer:add_to_cart' i.id %}" method="post">
            {% csrf_token %}
          <button type="submit" class="btn btn-primary">Add to cart</button>
          <a href="{% url 'customer:payment' %}" class="btn btn-primary" style="margin-left: 30px;">Buy now</a>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}

</div>

</div>








{% endblock %}

customer/templates/wishlist.html
{% extends 'masterpage1.html' %}
{% load static %}
{% block content %}



<style>
    #cart_table{
        width: 1100px;
        margin-left: -70px;
        font-size: large;
        text-align: center;
        margin-bottom: 50px;

        /* border: 1px solid black; */
        

    }

    #cart_table th {
        height: 50px;
        font-size: large;
        /* border: 1px solid black; */
    }
    img{
        height: 200px;
        width: 150px;
        
        
    }
     #add_to_btn {
    border: none;
    background-color: black;
    border-radius: 10px;
    color: white;
    width: 120px;
     height: 35px;
    }
    #add_to_btn:hover{
    background-color: rgb(235, 20, 20);
    color: black;
    }
    #remove_btn{
    border: none;
    background-color: black;
     border-radius: 10px;
    color: white;
    width: 120px;
    height: 35px;
    }
  
   #remove_btn:hover{
    background-color: rgb(235, 20, 20);
    color: black;
   }

  
</style>


 

</style>

<div class="container-fluid">
    <div class="row"  style=" background-color:rgb(240, 222, 222)">
        <h1 style="margin-top: 20px;margin-bottom: 30px;padding-left: 600px;">My Whishlist</h1>
    </div>
    
    <div class="row"style="background-color:rgb(240, 222, 222)">
        <div class="col-1">
    
        </div>
        <div class="col-10">
           <form action="" method="post">
            {% csrf_token %}
            <table id="cart_table">
                <tr>
                    <th style="width: 300px;">Product</th>
                    <th style="width: 300px;">Product Name</th>
                    <th style="width: 200px;">Price</th>
                    <th style="width: 200px;">Actions</th>
                    <th style="width: 200px;">Remove</th>
                    
                </tr>
                
                {% for item in wishlist_item %}

                <tr>
                    <td><img src="{{item.products.image.url}}" alt=""></td>
                    <td><b>{{item.products.name}}</b></td>
                    <td>{{item.products.price}}</td>
                    <form action="{% url 'customer:add_to_cart' item.products.id %}" method="post">
                        {% csrf_token %}
                        <td><button type="submit" id="add_to_btn">Add to Cart</button></td>
                    </form>
                    <form action="{% url 'customer:remove_from_wishlist' item.products.id %}" method="post">
                        {% csrf_token %}
                        <td><button type="submit" id="remove_btn">Remove</button></td>
                    </form>

                    </form>
                </tr>

                {% endfor %}
    
            </table>
           </form>
    
        </div>
        <div class="col-1" >
    
        </div>
    </div>
    
</div>











{% endblock %}

customer/templates/women.html
{% extends 'masterpage1.html' %}
{% load static %}
{% block content %}

<div class="container-fluid">
  <div class="row" style="text-align: center;">
    <h1 style="color: #B40431;">𝙻𝚎𝚝'𝚜 𝙴𝚡𝚙𝚕𝚘𝚛𝚎 Women's 𝚆𝚎𝚊𝚛</h1>
</div>

<div class="row" style="margin-bottom: 100px;">
  {% for i in products %}
    <div class="col-3">
        <div class="card" style="width: 18rem; margin-top: 50px">
        <img src="{{i.image.url}}" class="card-img-top" alt="..."  style="height: 450px;">
        <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">67% off <h4>Rs {{i.price}}</h4> </p>
          <form action="{% url 'customer:add_to_cart' i.id %}" method="post">
            {% csrf_token %}
          <a href="{% url 'customer:payment' %}" class="btn btn-primary">Buy now</a>
          <button type="submit" class="btn btn-primary" style="margin-left: 20px;">Add to cart</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}

</div>

</div>






















{% endblock %}